### ISSUE TITLE
Do you have any demos on jsfiddle.net?

### ISSUE THREAD

**Issue by JohnAReid** [chrisguttandin/angular-audio-context#1]
I looked at the angular-audio-context but not sure how to use it.

I am using the webkitSpeechRecognition system and would like to put a meter on the Angular web page to show that the microphone has soon activity (a bit like windows sound recorder).

I am also not sure whether the two systems would work together - i.e. can they both respond to microphone input as the same time?

**Comment by chrisguttandin** [comment]
Hi @JohnAReid, sorry for overlooking this issue for such a long time. I don't know how that could happen.

Given the fact that I never actually used the `webkitSpeechRecognition` myself, I think that it works in isolation. Which means that you cannot access the audio stream which it processes.

**Comment by JohnAReid** [comment]
That's ok - to be honest I forgot about it as well!
