### ISSUE TITLE
Set oscillator's  waveform type , recive an error.

### ISSUE THREAD

**Issue by davvoz** [chrisguttandin/angular-audio-context#270]
I try to set my oscillator waveform but recive on error . Insthead i can set others parameters (frequency,detune).
 

> import { AudioContext } from 'angular-audio-context';
 export class MyOscillator {
 constructor(private _audioContext: AudioContext) {
 }
 play(frequency: number, sustain: number, detune: number) {
    const osc = this._audioContext.createOscillator();
    osc.type = 'square';
    osc.frequency.setTargetAtTime(frequency, this._audioContext.currentTime, detune);
    osc.start(this._audioContext.currentTime);
    osc.stop(this._audioContext.currentTime + sustain / 500);
    osc.connect(this._audioContext.destination);
 }}

In chrome I recive this error 

> ERROR TypeError: Cannot set property type of [object Object] which has only a getter
    at MyOscillator.play (myOscillator.ts:14)
    at StepSequencerComponent.tick (step-sequencer.component.ts:88)
    at StepSequencerComponent.startStop (step-sequencer.component.ts:75)
    at Object.eval [as handleEvent] (StepSequencerComponent.html:2)
    at handleEvent (core.js:13540)
    at callWithDebugContext (core.js:15049)
    at Object.debugHandleEvent [as handleEvent] (core.js:14636)
    at dispatchEvent (core.js:9955)
    at eval (core.js:10580)
    at HTMLButtonElement.eval (platform-browser.js:2628)

In Edge

> [object Error]: {description: "Assignment to read-only properties is not allowed in strict mode", message: "Assignment to read-only properties is not allowed in strict mode", ngDebugContext: Object, ngErrorLogger: function() { [native code] }, number: -2146823243...}
description: "Assignment to read-only properties is not allowed in strict mode"
message: "Assignment to read-only properties is not allowed in strict mode"
ngDebugContext: Object
ngErrorLogger: function() { [native code] }
number: -2146823243
stack: "TypeError: Assignment to read-only properties is not allowed in strict mode at MyOscillator.prototype.play (eval code:15:9) at StepSequencerComponent.prototype.tick (eval code:82:9) at StepSequencerComponent.prototype.startStop (eval code:74:17) at Anonymous function (Function code:280:7) at handleEvent (eval code:13754:87) at callWithDebugContext (eval code:15263:9) at debugHandleEvent (eval code:14850:5) at dispatchEvent (eval code:10169:9) at Anonymous function (eval code:10794:31) at Anonymous function (eval code:2680:9)"

**Comment by chrisguttandin** [comment]
Hi @davvoz, thanks for reporting that issue. I had a brief look at the source code of the [standardized-audio-context](https://github.com/chrisguttandin/standardized-audio-context) package, which is used here to even out the differences of different browser APIs. It looks like the bug originates from there. I will try to fix it later today and will then notify you again.

**Comment by chrisguttandin** [comment]
Hi @davvoz, the bug you described should be gone when you update to version 13.0.12.

I'm closing this issue now. Please feel free to reopen it, if that was to optimistic.

**Comment by davvoz** [comment]
It works! Thank you
