### ISSUE TITLE
You can't connect an AudioParam to an AudioNode

### ISSUE THREAD

**Issue by davvoz** [chrisguttandin/angular-audio-context#276]
Hi dude.
In this page:
  [https://developer.mozilla.org/en-US/docs/Web/API/AudioNode/connect](url)
 I have read this: 
> The connect() method of the AudioNode interface lets you connect one of the node's outputs to a target, which may be either another AudioNode (thereby directing the sound data to the specified node) or an AudioParam, so that the node's output data is automatically used to change the value of that parameter over time.

But , when I try to connect an AudioParam to an audioNode , like this :
`let biquadFilter = this._audioContext.createBiquadFilter();
 let lfoGain = this._audioContext.createGain();
 lfoGain.connect(biquadFilter.frequency);`
I recive an error here: lfoGain.connect(biquadFilter.frequency).
This error: 

> message: 'Argument of type 'IAudioParam' is not assignable to parameter of type 'IAudioNode'.
  Property 'context' is missing in type 'IAudioParam'.

It's possible that I'm doing something wrong.
But ,I think the error is right because the IAudioNode interface connection methods is like this:

`connect(destination: IAudioNode, output?: number, input?: number): IAudioNode;` 
and not like this: 
`connect(destination: IAudioNode | IAudioParam , output?: number, input?: number): IAudioNode;`
...anyway I'm trying to talk about what I don't know .

**Comment by chrisguttandin** [comment]
Hi @davvoz, you're absolutely right. That should be possible. Unfortunately, I haven't implemented it yet. It's still marked as todo:

https://github.com/chrisguttandin/standardized-audio-context/blob/c53f48060d83b9e4a44f0f89564912519102660a/src/interfaces/audio-node.ts#L18

I will try to get it done later today.

**Comment by chrisguttandin** [comment]
Hi @davvoz, the use case you described should be possible now. Can you please double check that with the latest release (v13.0.29)?

**Comment by davvoz** [comment]
👍 Great! Now the connect method can take an AudioParameter as an argument . So i can try to do an LFO. Thank you @chrisguttandin .
