### ISSUE TITLE
Metadata Version Mismatch 

### ISSUE THREAD

**Issue by kireetig** [chrisguttandin/angular-audio-context#292]
Hi,
I am getting following error : 
**Metadata version mismatch for module /Users/kireeti/Downloads/Nextqbicle/node_modules/angular-audio-context/build/es2015/module.d.ts, found version 4, expected 3, resolving symbol AppModule in /Users/kireeti/Downloads/Nextqbicle/src/app/app.module.ts, resolving symbol AppModule in /Users/kireeti/Downloads/Nextqbicle/src/app/app.module.ts**

**Comment by chrisguttandin** [comment]
Hi @kireetig, can you please provide some more insights? When are you getting this error? What version of Angular and what version of this package are you using? As the word "metdata" is part of the error message, I guess it would also be interesting to know if you are using AoT or JiT mode.

**Comment by kireetig** [comment]
@chrisguttandin I found the issue it was due to i am using angular 4. I think backward compatibility was missing. when i was install version 11 it was working fine. Thanks for reply

**Comment by chrisguttandin** [comment]
Alright, I'm glad it works now. I will therefore close this issue.
