### ISSUE TITLE
How Use The isSupport 

### ISSUE THREAD

**Issue by Mehranh** [chrisguttandin/angular-audio-context#335]
Hi 
Please  help me to find that does browser support AudioContext ?
I cannot use this code : 

`constructor( @Inject(isSupported) public isSupported) `

this.isSupported() return ZoneAwarePromise ;

Do you have any demo to help use ?
thanks

**Comment by chrisguttandin** [comment]
hi @Mehranh,

the value which get's injected for the `isSupported` token is a function which returns a promise.

Can you please tell me a little more about the error you get or the problem you are trying to solve?

**Comment by chrisguttandin** [comment]
I'm glad to hear that. I will close the issue then.

**Comment by Mehranh** [comment]
Hi Christoph

I attached my code to this mail
*In all pelatfrom everething is good *
*but in iphones although browser is supported but songs not play*
*my demo is here : demo <http:18.217.218.163>*
*can you fix it on your library?*

-- 
*Mehran Hafizi*
*Web-based systems designer and developer *
*mob1: (+98) 936 470 7009 *

*mob2: (+98) 913 740 0847*
*Web : -*
* <https://ir.linkedin.com/pub/mehran-hafizi/93/599/481>**
<http://google.com/+MehranHafizi>*

import {EventEmitter, Injectable, OnInit} from '@angular/core';
import {AudioContext, IAudioBufferSourceNode, IAudioBuffer} from 'standardized-audio-context';
@Injectable()
export class AudioContextService implements OnInit {
  private audioContext: AudioContext;
  private audioBuffer: IAudioBuffer;
  private isSupportWebApi: boolean;
  bufferSource: IAudioBufferSourceNode;
  eventListner: EventEmitter<string> = new EventEmitter<string>();
  state = 'stop';
  bpm = 70;

  constructor() {
    this.createContext();
  }
  async fetchSample(url: string): Promise<any> {

    url = url.replace('{bpm}', this.bpm + 'bpm');

    this.eventListner.emit('fetching');
    this.state = 'fetching';
    return fetch(url)
      .then(response => response.arrayBuffer())
      .then(buffer => {
        return new Promise((resolve, reject) => {
          this.audioContext.decodeAudioData(
            buffer,
            resolve,
            reject
          );

        });
      });
  }

  createBuffer(numberOfChanel, length, rate): AudioBuffer {
    return this.audioContext.createBuffer(numberOfChanel, length, rate);
  }

  createContext() {
    try {
      this.audioContext = new AudioContext();

    } catch (e) {
      alert('your browser is not supported');
    }
  }

  playSample(url, bpm: number = null) {
    const self = this;
    if (this.state === 'playing') {
      this.stopSample();
    }
    this.fetchSample(url)
      .then(audioBuffer => {
        this.playBuffer(audioBuffer, 0);
      })
      .catch(error => {
        this.eventListner.emit('error');
        throw error;
      });
  }

  playBuffer(audioBuffer: IAudioBuffer, startTime) {
    const self = this;
    if (this.state === 'playing') {
      this.stopSample();
    }
    try {
      this.audioBuffer = audioBuffer;
      this.bufferSource = this.audioContext.createBufferSource();
      this.bufferSource.buffer = this.audioBuffer;
      this.bufferSource.connect(this.audioContext.destination);
      this.bufferSource.start(0, startTime);
      this.state = 'playing';
      this.eventListner.emit('playing');
      this.bufferSource.addEventListener('ended', function () {
        self.state = 'ended';
        self.eventListner.emit('ended');
        self.bufferSource.stop();
      });

    } catch (e) {
      alert(e);
    }

  }

  stopSample() {
    this.state = 'stop';
    this.eventListner.emit('stop');
    this.bufferSource.stop();
  }

  ngOnInit(): void {

  }

}
