### ISSUE TITLE
Cannot find name 'Omit'.

### ISSUE THREAD

**Issue by chetumayank** [chrisguttandin/angular-audio-context#418]
ERROR in node_modules/standardized-audio-context/build/es2018/types/native-panner-node.d.ts(1,41): error TS2304: Cannot find name 'Omit'.

**Comment by chrisguttandin** [comment]
Hi @chetumayank, the [Omit type was added in TypeScript v3.5](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-5.html#the-omit-helper-type). Updating TypeScript should solve the issue. Please feel free to reopen it if that's not the case.

**Comment by chetumayank** [comment]
I have upgraded the ts version from 3.2.2 to 3.5. We are unable to run the angular 7.3.9 and getting this error "ERROR in The Angular Compiler requires TypeScript >=3.1.1 and <3.3.0 but 3.5.1 was found instead.". Please provide the feedback or any suggestion.
