### ISSUE TITLE
Cannot find name 'Omit'.

### ISSUE THREAD

**Issue by chetumayank** [chrisguttandin/angular-audio-context#419]
I have upgraded the ts version from 3.2.2 to 3.5. We are unable to run the angular 7.3.9 and getting this error "ERROR in The Angular Compiler requires TypeScript >=3.1.1 and <3.3.0 but 3.5.1 was found instead.". Please provide the feedback or any suggestion.

**Comment by chrisguttandin** [comment]
In that case you can downgrade angular-audio-context to v22 which was the last version which supported Angular v7.

v23+ are compatible with Angular v8.

**Comment by chetumayank** [comment]
I have installed the version 20 and also 22 but still getting same error. I have used the angular v7.2 and  "typescript": "~3.2.2". Please provide suggestion.

**Comment by chrisguttandin** [comment]
Is your project publicly available that I could take a look at the dependency graph?

**Comment by chetumayank** [comment]
No its not publicly its on the local env. If you want I can share dependency here

**Comment by chrisguttandin** [comment]
I'm not sure if that helps. Do you have standardized-audio-context installed as well or only as transitive dependency of angular-audio-context?

**Comment by chetumayank** [comment]
we have install the standardized-audio-context version v21 latest any version compatibility with angular-audio-context version

**Comment by chrisguttandin** [comment]
Yes, that needs to be compatible as well.

For Angular v8 you can use the latest version of every package but for Angular v7 the following versions should work:

angular-audio-context v22.x.x
standardized-audio-context v20.x.x

**Comment by chetumayank** [comment]
@chrisguttandin  Thanks for your valuable time in issue. I have checked with several downgraded version and it is working with v15 for angular 7. Issue has been fixed.
