### ISSUE TITLE
 Cannot find name 'Omit'

### ISSUE THREAD

**Issue by spreadzp** [chrisguttandin/angular-audio-context#433]
when I to try start my angular app with  angular-audio-context I see error 
```
ERROR in node_modules/standardized-audio-context/build/es2018/types/native-panner-node.d.ts(1,41): error TS2304: Cannot find name 'Omit'.
```
How can I fix it?

**Comment by chrisguttandin** [comment]
Hi @spreadzp,

[Omit](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-5.html#the-omit-helper-type) is a helper type that was introduced in v3.5 of TypeScript. An update to that version should fix the problem.

Please let me know in case it still persists after the update.
