### ISSUE TITLE
Update for Angular 14?

### ISSUE THREAD

**Issue by w3geekery** [chrisguttandin/angular-audio-context#462]
I'm not sure what would be involved, but are there plans to update this so it could be used with Angular 14 anytime soon?
I wish I knew enough to be able to update a fork myself but alas I'm still lower on the learning curve...

Thank you for your work!!

**Comment by chrisguttandin** [comment]
Hi @w3geekery, as far as I can tell it should be fairly straightforward. I'm a bit short on time this week. I will try to do it early next week.

**Comment by chrisguttandin** [comment]
Hi @w3geekery, sorry that it took a bit longer. I published v33 a few minutes ago. It should be compatible with Angular v14. Please let me know if you encounter any issues.
